marvel_api/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from datetime import datetime
import uuid
from sqlalchemy.orm import backref
from werkzeug.security import generate_password_hash, check_password_hash
import secrets
from flask_login import LoginManager, UserMixin
from flask_marshmallow import Marshmallow


db = SQLAlchemy()
login_manager = LoginManager()
ma = Marshmallow()


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class User(db.Model, UserMixin):
    id = db.Column(db.String, primary_key = True)
    name = db.Column(db.String(70), unique=True, nullable=False)
    email = db.Column(db.String(80), nullable = False)
    password = db.Column(db.String, nullable = False)
    token = db.Column(db.String, nullable = False)
    date_created = db.Column(db.DateTime, default = datetime.utcnow)
    person = db.relationship('Person', backref='owner', lazy = True)

    def __init__(self, email, password, token = '', id = ''):
        self.id = self.set_id()
        self.email = email
        self.password = self.set_password(password)
        self.token = self.get_token(24) 

    def set_id(self):
        return str(uuid.uuid4())

    def set_password(self, password):
        self.pw_hash = generate_password_hash(password)
        return self.pw_hash
    
    def get_token(self, length):
        return secrets.token_hex(length)


class Person(db.Model):
    id = db.Column(db.String, primary_key = True)
    name = db.Column(db.String(150), nullable = False)
    description = db.Column(db.String(100), nullable = True)
    date_created = db.Column(db.DateTime, nullable = False, default = datetime.utcnow)
    owner = db.Column(db.String, db.ForeignKey('user.token'), nullable = False)

    def __init__(self, name, description, date_created, owner):
        self.name = name
        self.description = description
        self.date_created = date_created
        self.owner = owner

    def set_id(self):
        return (secrets.token_urlsafe())

class PersonSchema(ma.Schema):
    class Meta:
        fields = ['id', 'name', 'description', 'date_created', 'owner']

person_schema = PersonSchema()
persons_schema = PersonSchema(many=True)

marvel_api/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email

class UserLoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit_button = SubmitField()                 

marvel_api/__init__.py
from flask import Flask 
from config import Config
from .authentication.routes import auth
from .site.routes import site
from .api.routes import api 
from .models import db, User, login_manager
from flask_migrate import Migrate
from flask_cors import CORS 
from .helpers import JSONEncoder 
# marvel-env\Scripts\Activate
# set FLASK_APP=marvel-api
# set FLASK_ENV=development

app = Flask(__name__)
app.config.from_object(Config)
db.init_app(app)
login_manager.init_app(app)
login_manager.login_view = 'auth.signin'
migrate = Migrate(app, db)
app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)
CORS(app)

app.json_encoder = JSONEncoder

marvel_api/api/routes.py
from flask import Blueprint, request, jsonify
from marvel_api.helpers import token_required
from marvel_api.models import Person, db, person_schema, persons_schema

api = Blueprint('api', __name__, url_prefix='/api')




@api.route('/persons', methods=['POST'])
@token_required
def create_person(current_user_token):
    name = request.json['name']
    description = request.json['description']
    token = current_user_token.token

    print(f'TEST: {current_user_token.token}')

    person = person(name,description,user_token = token)

    db.session.add(person)
    db.session.commit()

    response = person_schema.dump(person)
    return jsonify(response)

@api.route('/persons', methods = ['GET'])
@token_required
def get_persons(current_user_token):
    owner = current_user_token.token
    persons = person.query.filter_by(user_token = owner).all()
    response = persons_schema.dump(persons)
    return jsonify(response)

@api.route('/persons/<id>', methods = ['GET'])
@token_required
def get_person(current_user_token, id):
    person = person.query.get(id)
    if person:
        print(f'Here is your person: {person.name}')
        response = person_schema.dump(person)
        return jsonify(response)
    else:
        return jsonify({'Error': 'That person does not exist!'})


@api.route('/persons/<id>', methods = ['POST', 'PUT'])
@token_required
def update_person(current_user_token, id):
    person = person.query.get(id)
    print(person)
    if person:
        person.name = request.json['name']
        person.description = request.json['description']
        person.user_token = current_user_token.token
        db.session.commit()

        response = person_schema.dump(person)
        return jsonify(response)
    else:
        return jsonify({'Error': 'That person does not exist!'})



@api.route('/persons/<id>', methods = ['DELETE'])
@token_required
def delete_person(current_user_token, id):
    person = person.query.get(id)
    if person:
        db.session.delete(person)
        db.session.commit()
        return jsonify({'Success': f'person ID #{person.id} has been deleted'})
    else:
        return jsonify({'Error': 'That person does not exist!'})

marvel_api/authentication/auth_templates/routes.py
from flask import Blueprint, render_template, request, url_for, flash, redirect
from marvel_api.forms import UserLoginForm
from marvel_api.models import User, db, check_password_hash
from flask_login import login_user, login_required, logout_user

auth = Blueprint('auth', __name__, template_folder='auth_templates')


@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        email = form.email.data
        password = form.password.data        
        new_user = User(email, password)
        db.session.add(new_user)
        db.session.commit()
        flash(f'You have successfully registered an account under {email}', 'user-created')
        return redirect(url_for('site.home'))
    return render_template('signup.html', form = form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        print(email, password)
        logged_user = User.query.filter(User.email == email).first()
        if logged_user and check_password_hash(logged_user.password, password):
            login_user(logged_user)
            flash('You were successfully logged in.', 'auth-success')
            
            return redirect(url_for('site.home'))

        else:
            flash('Your Email/Password is incorrect', 'auth-failed')
            return redirect(url_for('auth.signin'))


    return render_template('signin.html', form = form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have succesffuly logged out.', 'auth-success')
    return redirect(url_for('site.home'))

marvel_api/site/site_templates/routes.py
from flask import Blueprint, render_template
from flask_login import login_required

site = Blueprint('site', __name__, template_folder='site_templates')


@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
@login_required 
def profile():
    return render_template('profile.html')

marvel_api/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="assets/css/style.css">
<title>Marvel API</title>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{{ url_for('site.home') }}">Marvel API</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav">
                <li class="nav-item active">
                  <a class="nav-link" href="{{ url_for('site.home') }}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('site.profile') }}">Profile</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Pricing</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    User Portal
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{{ url_for('auth.signup') }}">Sign Up</a>
                    <a class="dropdown-item" href="{{ url_for('auth.signin') }}">Sign In<a>
                    <a class="dropdown-item" href="{{ url_for('auth.logout') }}">Log Out</a>
                  </div>
                </li>
              </ul>
            </div>
          </nav>
    </div>

    {% block %}

    {% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

marvel_api/templates/form.html
<form method="POST">
    {{ form.hiddne_tag() }}
    <div class="form-group">
        <fieldset>
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Enter email address") }}
        </fieldset>
        <fieldset>
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Enter password") }}
        </fieldset>
        {{ form.submit_button(class = "btn btn-dark")}}
    </div>
</form>